# Generated by Django 6.0.5 on 2026-07-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantprofile",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenantprofile",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pharmacy", "Pharmacy"),
                    ("provision_store", "Provision Store"),
                    ("supermarket", "Supermarket"),
                    ("electronic_store", "Electronic Store"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("tenant", "Tenant"), ("staff", "Staff")],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
