# Generated by Django 6.0.5 on 2026-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_sku_returntransaction_returnitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Product Code / SKU"
            ),
        ),
    ]
